
FIND_PROGRAM(Prove_EXECUTABLE "prove")

IF (Prove_EXECUTABLE)
	EXECUTE_PROCESS(COMMAND ${Prove_EXECUTABLE} "--version" OUTPUT_VARIABLE Prove_VERSION_UNPARSED)
	STRING(REGEX MATCH "TAP::Harness v(.*) and" _ "${Prove_VERSION_UNPARSED}")
	# ${CMAKE_MATCH_1} Now has Prove version

	FIND_PACKAGE(PackageHandleStandardArgs QUIET)
	FIND_PACKAGE_HANDLE_STANDARD_ARGS(Prove REQUIRED_VARS Prove_EXECUTABLE VERSION_VAR CMAKE_MATCH_1)
ENDIF()

